name: Push to Docker Hub
on:
  push:
    branches:
      - master
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use GCR
        run: |
          gcloud auth configure-docker --quiet

      - name: Build and push Docker image to GCR
        run: |
          IMAGE="gcr.io/enersyte/lastools"
          docker build -t $IMAGE .
          docker push $IMAGE
